In [1]:
import pandas as pd

In [4]:
df = pd.read_csv('data/processed-parallel/words.csv')

In [5]:
df

          yiddish    translit      source   yivo
0       געקליבענע   Geklibene         nli  False
1          שריפטן     shriftn         nli  False
2             דעם         Dem         nli  False
3           נאציס      Natsis         nli  False
4          יידישע     Yidishe         nli  False
...           ...         ...         ...    ...
191508     דיכטער     dikhter  verterbukh   True
191509   דיכטעריש  dikhterish  verterbukh   True
191510        דיק         dik  verterbukh   True
191511         \n      dikdek  verterbukh   True
191512     כלאָפּ       khlop  verterbukh   True

[191513 rows x 4 columns]